### ISSUE TITLE
Better LATEX block handling

### ISSUE THREAD

**Issue by gskorokhod** [gskorokhod/obsidian-garden#2]
Currently, a lot of edge cases when it comes to LATEX blocks are not handled properly:

- Matrices and other similar structures are not rendered correctly (see image)
![image](https://github.com/user-attachments/assets/1a8fe020-600d-46c9-8a33-76f26f751752)
- Complex LATEX blocks intermixed with text are completely broken
![image](https://github.com/user-attachments/assets/727fdc37-4397-4688-9198-1d367caaab37)
- Inline LATEX is sometimes not rendered correctly
![image](https://github.com/user-attachments/assets/0beb1e07-c7d2-44cc-ac5f-ca5021c65123)

# ToDo

- [ ] More robust parsing for LATEX
- [ ] Investigate different crates that render LATEX -> HTML
- [ ] Fix complex structures (e.g. matrices, cases, etc)
- [ ] Fix inline LATEX blocks
