### ISSUE TITLE
Better wikilnks

### ISSUE THREAD

**Issue by gskorokhod** [gskorokhod/obsidian-garden#3]
# ToDo

- [ ] Parse links to paragraps (e.g. `[[My Notes/Note 1#Heading 2]]`)
- [ ] Make such links functional (link to the appropriate heading by ID, not just the page)
- [ ] Render `![[previews]]` for wikilinks
- [ ] (Maybe) Hover preview for wikilinks?
